name: deepfake-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch-cpu
  - conda-forge::librosa
  - conda-forge::numpy
  - conda-forge::scikit-learn
  - conda-forge::streamlit
